### ISSUE TITLE
Configuration per instance

### ISSUE THREAD

**Issue by dideler** [elixir-waffle/waffle#21] opened 2019-10-23 10:47 UTC
The compile-time application config makes things such as buckets in multiple regions difficult. Is there a way to configure that per uploader at runtime? We can implement `asset_host/0`, but that also overrides other S3 config. Is there a cleaner way?

**Comment by achempion** [comment] 2019-10-23 11:06
Could you briefly describe a usecase for such configuration?

**Comment by dideler** [comment] 2019-10-23 14:01
Different uploaders for different media, and they use different S3 buckets. With the application config as

```
config :ex_aws, :s3, region: "eu-west-1"
```

It means all uploaders require their respective buckets to be in the same region.

If there's a requirement to use a different region for a new bucket, there's no easy way to have that configured since our application config is global. We'd have to do something like

```elixir
defmodule MyApp.File.Foo do
  use Waffle.Definition

  def asset_host, do: "https://#{bucket()}.s3.#{region()}.amazonaws.com"
  def bucket, do: "bucket-us"
  def region, do: "us-east-1
end
```

```elixir
defmodule MyApp.File.Bar do
  use Waffle.Definition

  def asset_host, do: "https://#{bucket()}.s3.#{region()}.amazonaws.com"
  def bucket, do: "bucket-eu"
  def region, do: "eu-west-1
end
```

Similar to how we can [specify a bucket](https://github.com/elixir-waffle/waffle#specify-multiple-buckets) per definition with `bucket/0`. Can we do something similar for region? In this case `region/0` isn't called by Waffle, it's an internal helper function for `asset_host/0`.

**Comment by achempion** [comment] 2019-10-23 14:23
Thank you.

It looks like we should allow to pass custom parameters to the `EXAws.request` function [here](https://github.com/elixir-waffle/waffle/blob/master/lib/waffle/storage/s3.ex#L49).

Here is an example from ExAws documentation to work with a different region
```elixir
ExAws.S3.list_objects("my-bucket") |> ExAws.request(region: "us-west-1")
```

**Comment by achempion** [comment] 2019-10-23 14:30
@dideler if you implemet a custom `asset_host` it will only affect the url generation, it shoudn't change the target region from ExAws perspective.

Do you have a working solution for now?

**Comment by kolorahl** [comment] 2020-03-23 22:40
I'll comment here although this is related to PR #31 as well.

I think that there needs to be a "common struct" that encapsulates information about a Waffle object, which I would argue should include versioning and transformation data. For example:

```elixir
%Waffle.Object{
  filename,
  directory,
  version,
  host,
  bucket,
  scope,
}
```

The idea, like @gullitmiranda proposed in PR #31, is to have something like what Plug has. Ultimately, there are _many_ steps that a Waffle file might go through before it is eventually stored, and lots of metadata that might be associated with it in all cases. I think the solution is to encapsulate as much of this data as possible in a common struct and then pass that around to all function calls, especially ones that can be overridden.

So `Waffle.Definition` might have the following functions:

```elixir
def bucket(_obj), do: Application.fetch_env!(:waffle, :bucket)
def asset_host(_obj), do: Application.get_env(:waffle, :asset_host)
def filename(%Waffle.Object{file: file}), do: Path.basename(file.file_name, Path.extname(file.file_name))
def storage_dir_prefix(_obj), do: Application.get_env(:waffle, :storage_dir_prefix, "")
def storage_dir(_obj), do: Application.get_env(:waffle, :storage_dir, "uploads")
def validate(_obj), do: true
def default_url(%Waffle.Object{version: version}), do: default_url(version)
def default_url(_), do: nil
```

This gives more power to the developer to choose how to handle their workflow by giving them as much information as possible.

**Comment by gabrielpra1** [comment] 2020-04-02 21:36
I had this problem in the past as well. 

In that time, `arc` was no longer maintained, `waffle` did not yet exist and I didn't like the way `arc` was designed, so I ended up creating a new library for uploads: https://github.com/jungsoft/uploadex

The idea there is to use elixir code as configuration through pattern matching, and with it we can customize upload options at the field level.

I'm sorry if it's inappropriate to post about another library here, but I thought it may help @dideler and maybe bring new ideas into waffle. If this is really not the place, feel free to delete this comment @achempion :)

**Comment by achempion** [comment] 2020-04-02 21:49
Thank you,

I'll look into implementation. Diversity is always great in opensource.

**Comment by wulymammoth** [comment] 2020-07-14 05:46
This is an interesting problem. I've not yet looked into the code into when each uploader is started, but I do notice that the bucket function is coupled to pulling a configuration at runtime with `Application.get_env`. One thing to consider is the use of [Vapor](https://github.com/keathley/vapor) for dynamic runtime configuration. I'm about to test-drive Waffle in a project for the first time and am just browsing the issues to see what I need to be aware of

**Comment by achempion** [comment] 2021-12-16 11:30
The issue addressed in https://github.com/elixir-waffle/waffle/pull/31

**Closed by achempion** 2021-12-16 11:30 UTC
